HAI
OBTW
	I HAS A child
	SUM OF 1 AN 2
	VISIBLE IT
	SUM OF 1.0 AN 2
	VISIBLE IT
	SUM OF 1 AN 2.0
	VISIBLE IT
	SUM OF 1.0 AN 2.0
	VISIBLE IT

	DIFF OF 1 AN 2
	VISIBLE IT
	PRODUKT OF 2 AN 3.0
	VISIBLE IT
	BIGGR OF 1.0 AN 3
	VISIBLE IT
	SMALLR OF 1.0 AN 3
	VISIBLE IT
	SUM OF 1 AN "2.0"
	VISIBLE IT
	DIFF OF "1.2" AN "3.2"
	VISIBLE IT
TLDR
  BTW  SUM OF PRODUKT OF 3 AN 5 AN BIGGR OF DIFF OF 17 AN 2 AN 5 MKAY
  SUM OF QUOSHUNT OF PRODUKT OF 3 AN 4 AN 2 AN 1
KTHXBYE